FROM up1998/selenium_chrome:latest

COPY config .
#COPY config/requirements.txt .
#RUN apt-get install -y\  
#  curl \
#  python3 \
#  python3-pip \
#  vim 
#RUN apt-get update
#RUN apt-get install vim curl -y
#RUN pip3 install -r requirements.txt -i https://mirrors.aliyun.com/pypi/simple/
CMD bash config.sh

